---
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:landonlite
    username: sa
    password: ""
  h2:
    console:
      enabled: true
#ebean:
#  db:
#    ddl:
#      generate: true
#      run: true
#datasource:
#  db:
#    databaseDriver: org.h2.Driver
#    databaseUrl: jdbc:h2:mem:landonlite
#    username: sa
#    password: ""
logging:
  level:
    io.ebean.SQL: DEBUG
    io.ebean.TXN: DEBUG
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头
